package net.menthor.editor.v2.ui.notify;

public enum NotificationType {

	ELEMENTS_ADDED,
	ELEMENTS_DRAGGED, 
	ELEMENTS_REMOVED, 
	ELEMENTS_MODIFIED, 
	ELEMENTS_MOVED, 
	ELEMENTS_RESIZED, 
	LABEL_TEXT_SET, 
	CONNECTION_NAVEGABILITY_SET, 
	CONNECTION_POINTS_RESET, 
	CONNECTION_POINT_EDITED, 
	CONNECTION_TYPE_CONVERTED,
	ELEMENTS_ALIGNED,
	VISIBILITY_CHANGED,
	ELEMENTS_COLORED
//}
}
