package net.menthor.resources.icons;

/**
* ============================================================================================
* Menthor Editor -- Copyright (c) 2015 
*
* This file is part of Menthor Editor. Menthor Editor is based on TinyUML and as so it is 
* distributed under the same license terms.
*
* Menthor Editor is free software; you can redistribute it and/or modify it under the terms 
* of the GNU General Public License as published by the Free Software Foundation; either 
* version 2 of the License, or (at your option) any later version.
*
* Menthor Editor is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
* See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along with Menthor Editor; 
* if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, 
* MA  02110-1301  USA
* ============================================================================================
*/

public enum IconType {
	
	MENTHOR_DELETE, MENTHOR_SAVE, MENTHOR_ERASE, MENTHOR_FOLDER, MENTHOR_ADD, 
	MENTHOR_SETTINGS, MENTHOR_DOC, MENTHOR_STATS, MENTHOR_ADD_GREEN, MENTHOR_EDIT, 
	MENTHOR_EXPORT, MENTHOR_IMPORT, MENTHOR_TO_FRONT, MENTHOR_ZOOM_EXPORT, MENTHOR_ZOOM_IN, 
	MENTHOR_ZOOM_OUT, MENTHOR_REDO, MENTHOR_UNDO, MENTHOR_SEARCH, MENTHOR_WARNING, MENTHOR_ERROR, 
	MENTHOR_GRID, MENTHOR_CHECK, MENTHOR_RECTILINEAR, MENTHOR_DIRECT, MENTHOR_TO_BACK, MENTHOR_PLAY, 
	MENTHOR_CLOSED, MENTHOR_OPEN, MENTHOR_EDIT_ROUND, MENTHOR_FIT, MENTHOR_PATTERN, MENTHOR_PICKER, 
	MENTHOR_COLOR_CHOOSER, MENTHOR_ALIGN_LEFT, MENTHOR_ALIGN_RIGHT, MENTHOR_ALIGN_BOTTOM, MENTHOR_ALIGN_TOP, 
	MENTHOR_ALIGN_HORIZONTAL, MENTHOR_ALIGN_VERTICAL, MENTHOR_DIAGRAM_TAB, MENTHOR_ADD_TAB, 
	MENTHOR_ADD_FOLDER, MENTHOR_TREE, MENTHOR_GEN_SET, MENTHOR_DOWNLOAD, MENTHOR_UPLOAD, MENTHOR_LINE, 
	MENTHOR_LINE2, MENTHOR_GEN_BLACK, MENTHOR_COMMENT, MENTHOR_PARTHOOD_BLACK, MENTHOR_DERIVATION, 
	MENTHOR_GRAPH, MENTHOR_GEN_WHITE, MENTHOR_PARTHOOD_M, MENTHOR_DASHED_LINE, MENTHOR_NOTE, MENTHOR_DOC_OCL, 
	MENTHOR_RED_BOX, MENTHOR_PARTHOOD_C, MENTHOR_PARTHOOD_Q, MENTHOR_BACK_BOXES, MENTHOR_CLASS, MENTHOR_PARTHOOD_E, 
	MENTHOR_DIAGRAM, MENTHOR_W3C, MENTHOR_SEMANTIC_WEB, MENTHOR_UML,
	
	//OLED
	NEW, OPEN, SAVE, CUT, COPY, PASTE, DELETE, UNDO, TOOLBOX, REDO, ERROR, WARNING, OUTPUT, OCLEDITOR, ABOUT, 
	ANNOTATION, MOUSE_POINTER, CLASS, ASSOCIATION, ASSOCIATION_ARROW, AGGREGATION, AGGREGATION_C, AGGREGATION_M, 
	AGGREGATION_Q, COMPOSITION, INHERITANCE, NOTE, NOTE_CONNECTOR, DIAGNOSTIC, VALIDATE, VERIFY_SETTINGS, VERIFY, 
	VERIFY_FILE, GENERATE_ALLOY, PARSE, VIEW, RECTILINEAR, STRAIGHT, DERIVATION, RULE, WINDOW, AUTO_SELECTION, PALETTE_OPEN, 
	PALETTE_CLOSED, GENERATE_OWL_SETTINGS, GENERATE_OWL, GENERATE_SBVR, GENERATE_TEXT, EA, IMPORT, EXPORT, UML, PICTURE,
	BACKGROUND_WELCOME, HEAD_WELCOME, NEW_PROJECT, NEW_DIAGRAM, OPEN_PROJECT, ISSUE_REPORT, NEXT, PACKAGE, ADD, REMOVE,
	GREEN_LIGHT, RED_LIGHT, EXCLUDE, GREY_LIGHT, ARROW_UP, COPYRIGHTS, ARROW_DOWN, ANTIPATTERN, PART_WHOLE_VALIDATION,
	DERIVERELATIONS, MENTHOR, NEMO, DIRECT, PATTERN, FIND, STATISTICS,
}
